[package]
name = "wayfarer"
version = "0.1.0"
authors = ["joel nises <joel.nises@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.3", features = ["canvas", "tokio"] }
palette = "0.5"
chrono = "0.4"
cpal = "0.13"