name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
      - uses: apt install libgtk-3-dev
      - run: cargo fmt --all -- --check
      - run: cargo check
      - run: cargo clippy -- -D warnings
      - run: cargo test
